### ISSUE TITLE
import docDate and source_url not work

### ISSUE THREAD

**Issue by yhsiang** [mysociety/sayit#484] opened 2015-05-13 07:17 UTC
Hi here is my akomantoso file.
```
<akomaNtoso>
    <debate>
        <meta>...</meta>
        <preface>
            <docDate date="2012-03-07"/>
            <docTitle>blah....</docTitle>
            <link href="http:/..."/>
        </preface>    
        <debateBody>...</debateBody>
   </debate>
</akomaNtoso>
```
import_akomantoso.py cant really get `self.start_date` and `source_url`

I made it work when I modified the code below
https://github.com/mysociety/sayit/blob/master/speeches/importers/import_akomantoso.py#L60
```
self.start_date = dateutil.parse(self.get_preface_tag(debate, 'docDate').get('date'))
```
https://github.com/mysociety/sayit/blob/master/speeches/importers/import_akomantoso.py#L80
```
source_url = self.get_preface_tag(debate, 'link').get('href') or ''
```

Am I wrong? Or can I send a PR for this ?

**Comment by dracos** [comment] 2015-05-13 14:35
Thanks for raising this. The issue is that the current importer appears to assume that `docDate` and `link` will not be self-closed elements, but will have some content, e.g. `The House met on <docDate date="2012-03-07">7th March 2012</docDate>`. I think your proposed changes would fail if the items weren't then present (as the return of `get_preface_tag` would be `None` which then does not have a `get()`); I've submitted something I hope works (changing the checks around the lines you mention to be `is not None` rather than just "truthiness") as #485 (along with your example as a test), let me know if that also works for you and then we can merge it in :)

**Comment by yhsiang** [comment] 2015-05-14 03:37
@dracos thx! it works for me :+1:

**Comment by johnfelipe** [comment] 2015-05-15 01:51
I can gitt pull and work?

**Comment by dracos** [comment] 2015-05-15 09:54
@yhsiang Great, now merged.
@johnfelipe I have merged this in now, yes, though it depends how you have installed/are using SayIt - you may need to e.g. rerun "pip install -r requirements.txt" to update the included SayIt application if you're using it within a different project, as I think you are.

**Closed by dracos** 2015-05-15 09:54 UTC
